databases:
  - name: esporte-mestre-db
    databaseName: esporte_mestre_production
    user: esporte_mestre_user
    plan: free

services:
  - type: web
    name: esporte-mestre
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esporte-mestre-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
